language: node_js
node_js:
  - "node"
  - "10"
  - "9"
  - "8"
  - "7"
#  - "6"
#  - "5"
#  - "4"

os:
  - linux
  - osx

compiler:
  - gcc

env:

#if: NOT branch = master
#if: NOT tag =~ ^[0-9]*.[0-9]*.[0-9]*

branches:
  only:
    - /^[0-9]+\.[0-9]+.[0-9]+/

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - uuid-dev

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8784d70ae92882b8923a
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
