language: node_js
node_js:
  - "node"
  - "7"
  - "6"
  - "5"
#  - "4"

os:
  - linux
  - osx

compiler:
  - gcc
#  - clang

env:
#  - CXX=g++-6
#  - clang-3.7

#matrix:
#  include:
#  - os: linux
#    compiler: gcc
#    env: CXX=g++-6
#  - os: osx
#    compiler: clang
#    env: 

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - uuid-dev

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8784d70ae92882b8923a
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always